export const APPLICATION_COMMANDS = {
  'CREATE_APPLICATION': 'create.channel.application',
  'ADD_APPLICATION': 'add.channel.application',
  'UPDATE_APPLICATION': 'update.channel.application',
  'REMOVE_APPLICATION': 'remove.channel.application',
  'MOVE_APPLICATION': 'move.channel.application',
  'DESTROY_APPLICATION': 'destroy.channel.application',
  'PUBLISH_APPLICATION': 'publish.channel.application',
  'UNPUBLISH_APPLICATION': 'unpublish.channel.application',
  'ADD_APPLICATION_PREHOOK': 'add.channel.application.prehook',
  'CREATE_APPLICATION_PREHOOK': 'create.channel.application.prehook',
  'UPDATE_APPLICATION_PREHOOK': 'update.channel.application.prehook',
  'REMOVE_APPLICATION_PREHOOK': 'remove.channel.application.prehook',
  'ADD_APPLICATION_WEBHOOK': 'add.channel.application.webhook',
  'CREATE_APPLICATION_WEBHOOK': 'create.channel.application.webhook',
  'UPDATE_APPLICATION_WEBHOOK': 'update.channel.application.webhook',
  'REMOVE_APPLICATION_WEBHOOK': 'remove.channel.application.webhook',
  'CREATE_APPLICATION_TRANSFORMER': 'create.channel.application.transformer',
  'UPDATE_APPLICATION_TRANSFORMER': 'update.channel.application.transformer',
  'ADD_APPLICATION_TRANSFORMER': 'add.channel.application.transformer',
  'REMOVE_APPLICATION_TRANSFORMER': 'remove.channel.application.transformer',
  'ADD_APPLICATION_ENDPOINT': 'add.channel.application.endpoint',
  'CREATE_APPLICATION_ENDPOINT': 'create.channel.application.endpoint',
  'UPDATE_APPLICATION_ENDPOINT': 'update.channel.application.endpoint',
  'REMOVE_APPLICATION_ENDPOINT': 'remove.channel.application.endpoint',
  'RUN_APPLICATION_ENDPOINT': 'run.channel.application.endpoint',
  'ADD_APPLICATION_KEY': 'add.channel.application.key',
  'CREATE_APPLICATION_KEY': 'create.channel.application.key',
  'UPDATE_APPLICATION_KEY': 'update.channel.application.key',
  'REMOVE_APPLICATION_KEY': 'remove.channel.application.key',

  'UPLOAD_APPLICATIONS': 'upload.channel.application',
  'PROCESS_UPLOADED_APPLICATIONS': 'process.upload.channel.application',
}
export const APPLICATION_ACTIONS = {
  'SUBSCRIBE_APPLICATION': 'channel.application.subscribe',

  'GET_APPLICATION': 'channel.application.get',
  'LIST_APPLICATIONS': 'channel.application.list',
  'LIST_APPLICATION_EVENTS': 'channel.application.event.list',
  'GET_APPLICATION_ENDPOINT': 'channel.application.endpoint.get',
  'LIST_APPLICATION_ENDPOINTS': 'channel.application.endpoint.list',
  'GET_APPLICATION_KEY': 'channel.application.key.get',
  'LIST_APPLICATION_KEYS': 'channel.application.key.list',
  'GET_APPLICATION_PREHOOK': 'channel.application.prehook.get',
  'LIST_APPLICATION_PREHOOKS': 'channel.application.prehook.list',
  'GET_APPLICATION_WEBHOOK': 'channel.application.webhook.get',
  'LIST_APPLICATION_WEBHOOKS': 'channel.application.webhook.list',
  'GET_APPLICATION_TRANSFORMER': 'channel.application.transformer.get',
  'LIST_APPLICATION_TRANSFORMERS': 'channel.application.transformer.list',

  'GET_APPLICATION_UPLOAD': 'channel.application.upload.get',
  'LIST_APPLICATION_UPLOADS': 'channel.application.upload.list',
}
export const APPLICATION_EVENTS = {
  'APPLICATION_CREATED': 'channel.application.created',
  'APPLICATION_ADDED': 'channel.application.added',
  'APPLICATION_UPDATED': 'channel.application.updated',
  'APPLICATION_MOVED': 'channel.application.moved',
  'APPLICATION_REMOVED': 'channel.application.removed',
  'APPLICATION_DESTROYED': 'channel.application.destroyed',
  'APPLICATION_PUBLISHED': 'channel.application.published',
  'APPLICATION_UNPUBLISHED': 'channel.application.unpublished',
  'APPLICATION_PREHOOK_ADDED': 'channel.application.prehook.added',
  'APPLICATION_PREHOOK_CREATED': 'channel.application.prehook.created',
  'APPLICATION_PREHOOK_UPDATED': 'channel.application.prehook.updated',
  'APPLICATION_PREHOOK_REMOVED': 'channel.application.prehook.removed',
  'APPLICATION_WEBHOOK_CREATED': 'channel.application.webhook.created',
  'APPLICATION_WEBHOOK_UPDATED': 'channel.application.webhook.updated',
  'APPLICATION_WEBHOOK_ADDED': 'channel.application.webhook.added',
  'APPLICATION_WEBHOOK_REMOVED': 'channel.application.webhook.removed',
  'APPLICATION_TRANSFORMER_CREATED': 'channel.application.transformer.created',
  'APPLICATION_TRANSFORMER_UPDATED': 'channel.application.transformer.updated',
  'APPLICATION_TRANSFORMER_ADDED': 'channel.application.transformer.added',
  'APPLICATION_TRANSFORMER_REMOVED': 'channel.application.transformer.removed',
  'APPLICATION_ENDPOINT_ADDED': 'channel.application.endpoint.added',
  'APPLICATION_ENDPOINT_REMOVED': 'channel.application.endpoint.removed',
  'APPLICATION_ENDPOINT_CREATED': 'channel.application.endpoint.created',
  'APPLICATION_ENDPOINT_UPDATED': 'channel.application.endpoint.updated',
  'APPLICATION_ENDPOINT_RAN': 'channel.application.endpoint.ran',
  'APPLICATION_KEY_ADDED': 'channel.application.key.added',
  'APPLICATION_KEY_REMOVED': 'channel.application.key.removed',
  'APPLICATION_KEY_CREATED': 'channel.application.key.created',
  'APPLICATION_KEY_UPDATED': 'channel.application.key.updated',

  'APPLICATIONS_UPLOADED': 'channel.application.uploaded.list',
  'APPLICATIONS_UPLOAD_PROCESSED': 'channel.application.upload.processed.list',
}
