export const CART_COMMANDS = {
  'CREATE_CART': 'create.channel.:channel_uuid.cart',
  'UPDATE_CART': 'update.channel.:channel_uuid.cart.:cart_uuid',
  'DESTROY_CART': 'destroy.channel.:channel_uuid.cart.:cart_uuid',
  'CHECKOUT_CART': 'checkout.channel.:channel_uuid.cart.:cart_uuid',
  'CLOSE_CART': 'close.channel.:channel_uuid.cart.:cart_uuid',
  'SET_CART_ORDER': 'set.channel.:channel_uuid.cart.:cart_uuid.order.:order_uuid',
  'SET_CART_CUSTOMER': 'set.channel.:channel_uuid.cart.:cart_uuid.customer.:customer_uuid',
  'SET_CART_USER': 'set.channel.:channel_uuid.cart.:cart_uuid.user.:user_uuid',
  'REMOVE_CART_CUSTOMER': 'remove.channel.:channel_uuid.cart.:cart_uuid.customer.:customer_uuid',
  'SET_CART_BILLING': 'set.channel.:channel_uuid.cart.:cart_uuid.address_billing',
  'SET_CART_SHIPPING': 'set.channel.:channel_uuid.cart.:cart_uuid.address_shipping',
  'SET_CART_PAYMENT': 'set.channel.:channel_uuid.cart.:cart_uuid.payment_details',
  'SET_CART_FULFILLMENT': 'set.channel.:channel_uuid.cart.:cart_uuid.fulfillment_details',
  'ADD_CART_SHIPPING_LINE': 'add.channel.:channel_uuid.cart.:cart_uuid.lines_shipping',
  'ADD_CART_TAX_LINE': 'add.channel.:channel_uuid.cart.:cart_uuid.lines_taxes',
  'ADD_CART_OVERRIDE_LINE': 'add.channel.:channel_uuid.cart.:cart_uuid.lines_pricing_overrides',
  'REMOVE_CART_SHIPPING_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.lines_shipping',
  'REMOVE_CART_TAX_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.lines_taxes',
  'REMOVE_CART_OVERRIDE_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.lines_pricing_overrides',
  'CALCULATE_CART': 'calculate.channel.:channel_uuid.cart.:cart_uuid',
  'CALCULATE_CARTS': 'calculate.channel.:channel_uuid.list.cart',

  'CREATE_CART_ITEM': 'create.channel.:channel_uuid.cart.:cart_uuid.item',
  'CREATE_CART_ITEMS': 'create.channel.:channel_uuid.cart.:cart_uuid.list.item',
  'UPDATE_CART_ITEM': 'update.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid',
  'UPDATE_CART_ITEMS': 'update.channel.:channel_uuid.cart.:cart_uuid.list.item',
  'SET_CART_ITEMS_CUSTOMER': 'set.channel.:channel_uuid.cart.:cart_uuid.item.list.customer',
  'REMOVE_CART_ITEM': 'remove.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid',
  'DESTROY_CART_ITEM': 'destroy.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid',
  'INCREASE_CART_ITEM_QUANTITY': 'increase.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.quantity',
  'DECREASE_CART_ITEM_QUANTITY': 'decrease.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.quantity',
  'CALCULATE_CART_ITEM': 'calculate.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid',
  'CALCULATE_CART_ITEMS': 'calculate.channel.:channel_uuid.cart.:cart_uuid.list.item',
  'SET_CART_ITEM_PAYMENT': 'set.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.payment_details',
  'SET_CART_ITEM_FULFILLMENT': 'set.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.fulfillment_details',
  'ADD_CART_ITEM_SHIPPING_LINE': 'add.channel.cart.:cart_uuid.item.:item_uuid.lines_shipping',
  'ADD_CART_ITEM_TAX_LINE': 'add.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_taxes',
  'ADD_CART_ITEM_OVERRIDE_LINE': 'add.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_pricing_overrides',
  'REMOVE_CART_ITEM_SHIPPING_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_shipping',
  'REMOVE_CART_ITEM_TAX_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_taxes',
  'REMOVE_CART_ITEM_OVERRIDE_LINE': 'remove.channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_pricing_overrides',
}

export const CART_ACTIONS = {
  'GET_CART': 'channel.cart.get',
  'GET_CART_BILLING': 'channel.cart.address_billing.get',
  'GET_CART_SHIPPING': 'channel.cart.address_shipping.get',
  'GET_CART_CUSTOMER': 'channel.cart.customer.get',
  'GET_CART_PAYMENT_DETAILS': 'channel.cart.payment_details.get',
  'GET_CART_FULFILLMENT_DETAILS': 'channel.cart.fulfillment_details.get',
  'LIST_CART_SHIPPING_LINES': 'channel.cart.lines_shipping.list',
  'LIST_CART_TAX_LINES': 'channel.cart.lines_taxes.list',
  'LIST_CART_OVERRIDE_LINES': 'channel.cart.lines_pricing_overrides.list',
  'LIST_CARTS': 'channel.cart.list',

  'GET_CART_ITEM': 'channel.cart.item.get',
  'LIST_CART_ITEMS': 'channel.cart.item.list',

  'GET_CART_ITEM_PAYMENT_DETAILS': 'channel.cart.item.payment_details.get',
  'GET_CART_ITEM_FULFILLMENT_DETAILS': 'channel.cart.item.fulfillment_details.get',

  'LIST_CART_ITEM_SHIPPING_LINES': 'channel.cart.item.lines_shipping.list',
  'LIST_CART_ITEM_TAX_LINES': 'channel.cart.item.lines_taxes.list',
  'LIST_CART_ITEM_OVERRIDE_LINES': 'channel.cart.item.lines_pricing_overrides.list',

  'LIST_CART_EVENTS': 'channel.cart.event.list',
}

export const CART_EVENTS = {
  'CART_CREATED': 'channel.:channel_uuid.cart.:cart_uuid.created',
  'CART_UPDATED': 'channel.:channel_uuid.cart.:cart_uuid.updated',
  'CART_DESTROYED': 'channel.:channel_uuid.cart.:cart_uuid.destroyed',

  'CART_CHECKED_OUT': 'channel.:channel_uuid.cart.:cart_uuid.checked_out',
  'CART_CLOSED': 'channel.:channel_uuid.cart.:cart_uuid.closed',
  'CART_ORDER_SET': 'channel.:channel_uuid.cart.:cart_uuid.order.:order_uuid.set',
  'CART_CUSTOMER_SET': 'channel.:channel_uuid.cart.:cart_uuid.customer.:customer_uuid.set',
  'CART_USER_SET': 'channel.:channel_uuid.cart.:cart_uuid.user.:user_uuid.set',
  'CART_CUSTOMER_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.customer.:customer_uuid.removed',
  'CART_BILLING_SET': 'channel.:channel_uuid.cart.:cart_uuid.address_billing.set',
  'CART_SHIPPING_SET': 'channel.:channel_uuid.cart.:cart_uuid.address_shipping.set',
  'CART_PAYMENT_SET': 'channel.:channel_uuid.cart.:cart_uuid.payment_details.set',
  'CART_FULFILLMENT_SET': 'channel.:channel_uuid.cart.:cart_uuid.fulfillment_details.set',
  'CART_SHIPPING_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.lines_shipping.added',
  'CART_TAX_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.lines_taxes.added',
  'CART_OVERRIDE_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.lines_pricing_overrides.added',
  'CART_SHIPPING_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.lines_shipping.removed',
  'CART_TAX_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.lines_taxes.removed',
  'CART_OVERRIDE_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.lines_pricing_overrides.removed',
  'CART_CALCULATED': 'channel.:channel_uuid.cart.:cart_uuid.calculated',
  'CARTS_CALCULATED': 'channel.:channel_uuid.cart.:cart_uuid.calculated.list',

  'CART_ITEM_CREATED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.created',
  'CART_ITEMS_CREATED': 'channel.:channel_uuid.cart.:cart_uuid.item.created.list',
  'CART_ITEMS_CUSTOMER_SET': 'channel.:channel_uuid.cart.:cart_uuid.item.customer.set.list',
  'CART_ITEM_UPDATED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.updated',
  'CART_ITEMS_UPDATED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.updated.list',
  'CART_ITEM_QUANTITY_INCREASED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.quantity.increased',
  'CART_ITEM_QUANTITY_DECREASED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.quantity.decreased',
  'CART_ITEM_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.removed',
  'CART_ITEM_DESTROYED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.destroyed',
  'CART_ITEM_CALCULATED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.calculated',
  'CART_ITEMS_CALCULATED': 'channel.:channel_uuid.cart.:cart_uuid.item.calculated.list',
  'CART_ITEM_PAYMENT_SET': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.payment_details.set',
  'CART_ITEM_FULFILLMENT_SET': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.fulfillment_details.set',
  'CART_ITEM_SHIPPING_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_shipping.added',
  'CART_ITEM_TAX_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_taxes.added',
  'CART_ITEM_OVERRIDE_LINE_ADDED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_pricing_overrides.added',
  'CART_ITEM_SHIPPING_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_shipping.removed',
  'CART_ITEM_TAX_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_taxes.removed',
  'CART_ITEM_OVERRIDE_LINE_REMOVED': 'channel.:channel_uuid.cart.:cart_uuid.item.:item_uuid.lines_pricing_overrides.removed',
}
