export const CART_COMMANDS = {
  'CREATE_CART': 'create.channel.cart',
  'UPDATE_CART': 'update.channel.cart',
  'DESTROY_CART': 'destroy.channel.cart',
  'CHECKOUT_CART': 'checkout.channel.cart',
  'CLOSE_CART': 'close.channel.cart',
  'SET_CART_ORDER': 'set.channel.cart.order',
  'SET_CART_CUSTOMER': 'set.channel.cart.customer',
  'SET_CART_USER': 'set.channel.cart.user',
  'REMOVE_CART_CUSTOMER': 'remove.channel.cart.customer',
  'SET_CART_BILLING': 'set.channel.cart.address_billing',
  'SET_CART_SHIPPING': 'set.channel.cart.address_shipping',
  'SET_CART_PAYMENT': 'set.channel.cart.payment_details',
  'SET_CART_FULFILLMENT': 'set.channel.cart.fulfillment_details',
  'ADD_CART_SHIPPING_LINE': 'add.channel.cart.lines_shipping',
  'ADD_CART_TAX_LINE': 'add.channel.cart.lines_taxes',
  'ADD_CART_OVERRIDE_LINE': 'add.channel.cart.lines_pricing_overrides',
  'REMOVE_CART_SHIPPING_LINE': 'remove.channel.cart.lines_shipping',
  'REMOVE_CART_TAX_LINE': 'remove.channel.cart.lines_taxes',
  'REMOVE_CART_OVERRIDE_LINE': 'remove.channel.cart.lines_pricing_overrides',
  'CALCULATE_CART': 'calculate.channel.cart',
  'CALCULATE_CARTS': 'calculate.channel.cart.list',

  'CREATE_CART_ITEM': 'create.channel.cart.item',
  'CREATE_CART_ITEMS': 'create.channel.cart.item.list',
  'UPDATE_CART_ITEM': 'update.channel.cart.item',
  'UPDATE_CART_ITEMS': 'update.channel.cart.item.list',
  'SET_CART_ITEMS_CUSTOMER': 'set.channel.cart.item.customer.list',
  'REMOVE_CART_ITEM': 'remove.channel.cart.item',
  'DESTROY_CART_ITEM': 'destroy.channel.cart.item',
  'INCREASE_CART_ITEM_QUANTITY': 'increase.channel.cart.item.quantity',
  'DECREASE_CART_ITEM_QUANTITY': 'decrease.channel.cart.item.quantity',
  'CALCULATE_CART_ITEM': 'calculate.channel.cart.item',
  'CALCULATE_CART_ITEMS': 'calculate.channel.cart.item.list',
  'SET_CART_ITEM_PAYMENT': 'set.channel.cart.item.payment_details',
  'SET_CART_ITEM_FULFILLMENT': 'set.channel.cart.item.fulfillment_details',
  'ADD_CART_ITEM_SHIPPING_LINE': 'add.channel.cart.item.lines_shipping',
  'ADD_CART_ITEM_TAX_LINE': 'add.channel.cart.item.lines_taxes',
  'ADD_CART_ITEM_OVERRIDE_LINE': 'add.channel.cart.item.lines_pricing_overrides',
  'REMOVE_CART_ITEM_SHIPPING_LINE': 'remove.channel.cart.item.lines_shipping',
  'REMOVE_CART_ITEM_TAX_LINE': 'remove.channel.cart.item.lines_taxes',
  'REMOVE_CART_ITEM_OVERRIDE_LINE': 'remove.channel.cart.item.lines_pricing_overrides',
}

export const CART_ACTIONS = {
  'GET_CART': 'channel.cart.get',
  'GET_CART_BILLING': 'channel.cart.address_billing.get',
  'GET_CART_SHIPPING': 'channel.cart.address_shipping.get',
  'GET_CART_CUSTOMER': 'channel.cart.customer.get',
  'GET_CART_PAYMENT_DETAILS': 'channel.cart.payment_details.get',
  'GET_CART_FULFILLMENT_DETAILS': 'channel.cart.fulfillment_details.get',
  'LIST_CART_SHIPPING_LINES': 'channel.cart.lines_shipping.list',
  'LIST_CART_TAX_LINES': 'channel.cart.lines_taxes.list',
  'LIST_CART_OVERRIDE_LINES': 'channel.cart.lines_pricing_overrides.list',
  'LIST_CARTS': 'channel.cart.list',

  'GET_CART_ITEM': 'channel.cart.item.get',
  'LIST_CART_ITEMS': 'channel.cart.item.list',

  'GET_CART_ITEM_PAYMENT_DETAILS': 'channel.cart.item.payment_details.get',
  'GET_CART_ITEM_FULFILLMENT_DETAILS': 'channel.cart.item.fulfillment_details.get',

  'LIST_CART_ITEM_SHIPPING_LINES': 'channel.cart.item.lines_shipping.list',
  'LIST_CART_ITEM_TAX_LINES': 'channel.cart.item.lines_taxes.list',
  'LIST_CART_ITEM_OVERRIDE_LINES': 'channel.cart.item.lines_pricing_overrides.list',

  'LIST_CART_EVENTS': 'channel.cart.event.list',
}

export const CART_EVENTS = {}
