export const COLLECTION_COMMANDS = {
  'CREATE_COLLECTION': 'create.channel.collection',
  'ADD_COLLECTION': 'add.channel.collection',
  'MOVE_COLLECTION': 'move.channel.collection',
  'PUBLISH_COLLECTION': 'publish.channel.collection',
  'UNPUBLISH_COLLECTION': 'unpublish.channel.collection',
  'UPDATE_COLLECTION': 'update.channel.collection',
  'REMOVE_COLLECTION': 'remove.channel.collection',
  'DESTROY_COLLECTION': 'destroy.channel.collection',
  'UPLOAD_COLLECTIONS': 'upload.channel.collection',
  'PROCESS_UPLOADED_COLLECTIONS': 'process.upload.channel.collection',
  'UPLOAD_COLLECTION_METADATA': 'upload.channel.collection.metadata.list',
  'PROCESS_UPLOADED_COLLECTION_METADATA': 'process.upload.channel.collection.metadata.list',

  // Alias
  'ADD_COLLECTION_COLLECTION': 'add.channel.collection',
  'MOVE_COLLECTION_COLLECTION': 'move.channel.collection',
  'REMOVE_COLLECTION_COLLECTION': 'remove.channel.collection',

  'ADD_COLLECTION_PRODUCT': 'add.channel.collection.product',
  'ADD_COLLECTION_PRODUCTS': 'add.channel.collection.product.list',
  'MOVE_COLLECTION_PRODUCT': 'move.channel.collection.product',
  'REMOVE_COLLECTION_PRODUCT': 'remove.channel.collection.product',
  'ADD_COLLECTION_BILLING_MODEL': 'add.channel.collection.billing_model',
  'ADD_COLLECTION_BILLING_MODELS': 'add.channel.collection.billing_model.list',
  'MOVE_COLLECTION_BILLING_MODEL': 'move.channel.collection.billing_model',
  'REMOVE_COLLECTION_BILLING_MODEL': 'remove.channel.collection.billing_model',
  'ADD_COLLECTION_OFFER': 'add.channel.collection.offer',
  'ADD_COLLECTION_OFFERS': 'add.channel.collection.offer.list',
  'MOVE_COLLECTION_OFFER': 'move.channel.collection.offer',
  'REMOVE_COLLECTION_OFFER': 'remove.channel.collection.offer',
  'ADD_COLLECTION_CUSTOMER': 'add.channel.collection.customer',
  'ADD_COLLECTION_CUSTOMERS': 'add.channel.collection.customer.list',
  'MOVE_COLLECTION_CUSTOMER': 'move.channel.collection.customer',
  'REMOVE_COLLECTION_CUSTOMER': 'remove.channel.collection.customer',

  'ADD_COLLECTION_IMAGE': 'add.channel.collection.image',
  'ADD_COLLECTION_IMAGES': 'add.channel.collection.image.list',
  'UPDATE_COLLECTION_IMAGE': 'update.channel.collection.image',
  'MOVE_COLLECTION_IMAGE': 'move.channel.collection.image',
  'REMOVE_COLLECTION_IMAGE': 'remove.channel.collection.image',
}
export const COLLECTION_ACTIONS = {
  'GET_COLLECTION': 'channel.collection.get',
  'FIND_COLLECTION': 'channel.collection.get', // ALIAS
  'GET_COLLECTION_PARENT': 'channel.collection.parent.get',
  'LIST_COLLECTIONS': 'channel.collection.list',
  'FIND_COLLECTIONS': 'channel.collection.list', // ALIAS
  'LIST_COLLECTION_CHILDREN': 'channel.collection.children.list',
  'LIST_COLLECTION_SIBLINGS': 'channel.collection.siblings.list',
  'LIST_COLLECTION_DESCENDANTS': 'channel.collection.descendant.list',
  'LIST_COLLECTION_ANCESTORS': 'channel.collection.ancestor.list',
  'GET_COLLECTION_CUSTOMER': 'channel.collection.customer.get',
  'LIST_COLLECTION_CUSTOMERS': 'channel.collection.customer.list',
  'LIST_COLLECTION_EVENTS': 'channel.collection.event.list',
  'GET_COLLECTION_PRODUCT': 'channel.collection.product.get',
  'LIST_COLLECTION_PRODUCTS': 'channel.collection.product.list',
  'GET_COLLECTION_BILLING_MODEL': 'channel.collection.billing_model.get',
  'LIST_COLLECTION_BILLING_MODELS': 'channel.collection.billing_model.list',
  'GET_COLLECTION_OFFER': 'channel.collection.offer.get',
  'LIST_COLLECTION_OFFERS': 'channel.collection.offer.list',

  'GET_COLLECTION_UPLOAD_RESULT': 'channel.collection.upload_result.get',
  'LIST_COLLECTION_UPLOAD_RESULTS': 'channel.collection.upload_result.list',
  'GET_COLLECTION_UPLOAD': 'channel.collection.upload.get',
  'LIST_COLLECTION_UPLOADS': 'channel.collection.upload.list',

  'GET_COLLECTION_METADATA_UPLOAD_RESULT': 'channel.collection.metadata.upload_result.get',
  'LIST_COLLECTION_METADATA_UPLOAD_RESULTS': 'channel.collection.metadata.upload_result.list',
  'GET_COLLECTION_METADATA_UPLOAD': 'channel.collection.metadata.upload.get',
  'LIST_COLLECTION_METADATA_UPLOADS': 'channel.collection.metadata.upload.list',

  'GET_COLLECTION_IMAGE': 'channel.collection.image.get',
  'LIST_COLLECTION_IMAGES': 'channel.collection.image.list',

  'GET_PUBLIC_COLLECTION': 'channel.public.collection.get',
  'LIST_PUBLIC_COLLECTIONS': 'channel.public.collection.list',

  'GET_PUBLIC_COLLECTION_PRODUCT': 'channel.public.collection.product.get',
  'LIST_PUBLIC_COLLECTION_PRODUCTS': 'channel.public.collection.product.list',

  // CATEGORIES (collections)
  'GET_CATEGORY': 'channel.category.get',
  'GET_CATEGORY_PARENT': 'channel.category.parent.get',
  'LIST_CATEGORIES': 'channel.category.list',
  'LIST_CATEGORY_CHILDREN': 'channel.category.children.list',
  'LIST_CATEGORY_SIBLINGS': 'channel.category.siblings.list',
  'LIST_CATEGORY_DESCENDANTS': 'channel.category.descendant.list',
  'LIST_CATEGORY_ANCESTORS': 'channel.category.ancestor.list',
  'LIST_CATEGORY_EVENTS': 'channel.category.event.list',
  'GET_CATEGORY_PRODUCT': 'channel.category.product.get',
  'LIST_CATEGORY_PRODUCTS': 'channel.category.product.list',
  'GET_PUBLIC_CATEGORY_PRODUCT': 'channel.public.category.product.get',
  'LIST_PUBLIC_CATEGORY_PRODUCTS': 'channel.public.category.product.list',

  'GET_CATEGORY_IMAGE': 'channel.category.image.get',
  'LIST_CATEGORY_IMAGES': 'channel.category.image.list',

  'GET_PUBLIC_CATEGORY': 'channel.public.category.get',
  'LIST_PUBLIC_CATEGORIES': 'channel.public.category.list',
  'GET_PUBLIC_CATEGORY_PARENT': 'channel.public.category.parent.get',
  'LIST_PUBLIC_CATEGORY_CHILDREN': 'channel.public.category.children.list',
  'LIST_PUBLIC_CATEGORY_SIBLINGS': 'channel.public.category.siblings.list',
  'LIST_PUBLIC_CATEGORY_DESCENDANTS': 'channel.public.category.descendant.list',
  'LIST_PUBLIC_CATEGORY_ANCESTORS': 'channel.public.category.ancestor.list',
  'GET_PUBLIC_CATEGORY_OFFER': 'channel.public.category.offer.get',
  'LIST_PUBLIC_CATEGORY_OFFERS': 'channel.public.category.offer.list',

  // CAMPAIGNS (Collections)
  'GET_CAMPAIGN': 'channel.campaign.get',
  'GET_CAMPAIGN_PARENT': 'channel.campaign.parent.get',
  'LIST_CAMPAIGNS': 'channel.campaign.list',
  'LIST_CAMPAIGN_CHILDREN': 'channel.campaign.children.list',
  'LIST_CAMPAIGN_SIBLINGS': 'channel.campaign.siblings.list',
  'LIST_CAMPAIGN_DESCENDANTS': 'channel.campaign.descendant.list',
  'LIST_CAMPAIGN_ANCESTORS': 'channel.campaign.ancestor.list',
  'LIST_CAMPAIGN_EVENTS': 'channel.campaign.event.list',
  // 'GET_CAMPAIGN_PRODUCT': 'channel.campaign.product.get',
  // 'LIST_CAMPAIGN_PRODUCTS': 'channel.campaign.product.list',
  'GET_CAMPAIGN_BILLING_MODEL': 'channel.campaign.billing_model.get',
  'LIST_CAMPAIGN_BILLING_MODELS': 'channel.campaign.billing_model.list',
  'GET_CAMPAIGN_OFFER': 'channel.campaign.offer.get',
  'LIST_CAMPAIGN_OFFERS': 'channel.campaign.offer.list',
  'GET_CAMPAIGN_OFFER_VARIANT': 'channel.campaign.offer.variant.get',
  'LIST_CAMPAIGN_OFFER_VARIANTS': 'channel.campaign.offer.variant.list',
  'GET_CAMPAIGN_CUSTOMER': 'channel.campaign.customer.get',
  'LIST_CAMPAIGN_CUSTOMERS': 'channel.campaign.customer.list',

  'GET_CAMPAIGN_IMAGE': 'channel.campaign.image.get',
  'LIST_CAMPAIGN_IMAGES': 'channel.campaign.image.list',

  'GET_PUBLIC_CAMPAIGN': 'channel.public.campaign.get',
  'LIST_PUBLIC_CAMPAIGNS': 'channel.public.campaign.list',
  'GET_PUBLIC_CAMPAIGN_PARENT': 'channel.public.campaign.parent.get',
  'LIST_PUBLIC_CAMPAIGN_CHILDREN': 'channel.public.campaign.children.list',
  'LIST_PUBLIC_CAMPAIGN_SIBLINGS': 'channel.public.campaign.siblings.list',
  'LIST_PUBLIC_CAMPAIGN_DESCENDANTS': 'channel.public.campaign.descendant.list',
  'LIST_PUBLIC_CAMPAIGN_ANCESTORS': 'channel.public.campaign.ancestor.list',
  'GET_PUBLIC_CAMPAIGN_OFFER': 'channel.public.campaign.offer.get',
  'LIST_PUBLIC_CAMPAIGN_OFFERS': 'channel.public.campaign.offer.list',
  'GET_PUBLIC_CAMPAIGN_OFFER_VARIANT': 'channel.public.campaign.offer.variant.get',
  'LIST_PUBLIC_CAMPAIGN_OFFER_VARIANTS': 'channel.public.campaign.offer.variant.list',


  'GET_FULFILLMENT_ITEM': 'channel.fulfillment.item.get',
  'LIST_FULFILLMENT_ITEMS': 'channel.fulfillment.item.list',
  'GET_FULFILLMENT_SERVICE': 'channel.fulfillment_service.get',
  'LIST_FULFILLMENT_SERVICES': 'channel.fulfillment_service.list',
  'GET_FULFILLMENT_SERVICE_FULFILLMENT': 'channel.fulfillment_service.fulfillment.get',
  'LIST_FULFILLMENT_SERVICE_FULFILLMENTS': 'channel.fulfillment_service.fulfillment.list',

  'GET_FULFILLMENT_SERVICE_EVENT': 'channel.fulfillment_service.event.get',
  'LIST_FULFILLMENT_SERVICE_EVENTS': 'channel.fulfillment_service.event.list',

  'GET_FULFILLMENT_SERVICE_UPLOAD': 'channel.fulfillment_service.upload.get',
  'LIST_FULFILLMENT_SERVICE_UPLOADS': 'channel.fulfillment_service.upload.list'
}
export const COLLECTION_EVENTS = {
  'COLLECTION_CREATED': 'channel.collection.created',
  'COLLECTION_ADDED': 'channel.collection.added',
  'COLLECTION_MOVED': 'channel.collection.moved',
  'COLLECTION_PUBLISHED': 'channel.collection.published',
  'COLLECTION_UNPUBLISHED': 'channel.collection.unpublished',
  'COLLECTION_UPDATED': 'channel.collection.updated',
  'COLLECTION_REMOVED': 'channel.collection.removed',
  'COLLECTION_DESTROYED': 'channel.collection.destroyed',
  'COLLECTIONS_UPLOADED': 'channel.collection.uploaded.list',
  'COLLECTIONS_UPLOAD_PROCESSED': 'channel.collection.upload.processed.list',
  'COLLECTION_COLLECTION_ADDED': 'channel.collection.added',
  'COLLECTION_COLLECTION_MOVED': 'channel.collection.moved',
  'COLLECTION_COLLECTION_REMOVED': 'channel.collection.removed',
  'COLLECTION_PRODUCT_ADDED': 'channel.collection.product.added',
  'COLLECTION_PRODUCTS_ADDED': 'channel.collection.product.added.list',
  'COLLECTION_PRODUCT_MOVED': 'channel.collection.product.moved',
  'COLLECTION_PRODUCT_REMOVED': 'channel.collection.product.removed',
  'COLLECTION_OFFER_ADDED': 'channel.collection.offer.added',
  'COLLECTION_OFFERS_ADDED': 'channel.collection.offer.added.list',
  'COLLECTION_OFFER_MOVED': 'channel.collection.offer.moved',
  'COLLECTION_OFFER_REMOVED': 'channel.collection.offer.removed',
  'COLLECTION_CUSTOMER_ADDED': 'channel.collection.customer.added',
  'COLLECTION_CUSTOMERS_ADDED': 'channel.collection.customer.added.list',
  'COLLECTION_CUSTOMER_MOVED': 'channel.collection.customer.moved',
  'COLLECTION_CUSTOMER_REMOVED': 'channel.collection.customer.removed',
  'COLLECTION_BILLING_MODEL_ADDED': 'channel.collection.billing_model.added',
  'COLLECTION_BILLING_MODELS_ADDED': 'channel.collection.billing_model.added.list',
  'COLLECTION_BILLING_MODEL_MOVED': 'channel.collection.billing_model.moved',
  'COLLECTION_BILLING_MODEL_REMOVED': 'channel.collection.billing_model.removed',

  'COLLECTION_IMAGE_ADDED': 'channel.collection.image.added',
  'COLLECTION_IMAGES_ADDED': 'channel.collection.image.added.list',
  'COLLECTION_IMAGE_UPDATED': 'channel.collection.image.updated',
  'COLLECTION_IMAGE_MOVED': 'channel.collection.image.moved',
  'COLLECTION_IMAGE_REMOVED': 'channel.collection.image.removed',
}
