import {APPLICATION_ACTIONS, APPLICATION_COMMANDS, APPLICATION_EVENTS} from './application'
import {BILLING_MODEL_ACTIONS, BILLING_MODEL_COMMANDS, BILLING_MODEL_EVENTS} from './billing_model'
import {CART_ACTIONS, CART_COMMANDS, CART_EVENTS} from './cart'
import {COLLECTION_ACTIONS, COLLECTION_COMMANDS, COLLECTION_EVENTS} from './collection'
import {COUNTRY_ACTIONS, COUNTRY_COMMANDS, COUNTRY_EVENTS} from './country'
import {CUSTOMER_ACTIONS, CUSTOMER_COMMANDS, CUSTOMER_EVENTS} from './customer'
import {FEED_ACTIONS, FEED_COMMANDS, FEED_EVENTS} from './feed'
import {FULFILLMENT_ACTIONS, FULFILLMENT_COMMANDS, FULFILLMENT_EVENTS} from './fulfillment'
import {GATEWAY_ACTIONS, GATEWAY_COMMANDS, GATEWAY_EVENTS} from './gateway'
import {OFFER_ACTIONS, OFFER_COMMANDS, OFFER_EVENTS} from './offer'
import {ORDER_ACTIONS, ORDER_COMMANDS, ORDER_EVENTS} from './order'
import {PERMISSION_ACTIONS, PERMISSION_COMMANDS, PERMISSION_EVENTS} from './permission'
import {SUBSCRIPTION_ACTIONS, SUBSCRIPTION_COMMANDS, SUBSCRIPTION_EVENTS} from './subscription'
import {TASK_ACTIONS, TASK_COMMANDS, TASK_EVENTS} from './task'
import {TRANSACTION_ACTIONS, TRANSACTION_COMMANDS, TRANSACTION_EVENTS} from './transaction'
import {USER_ACTIONS, USER_COMMANDS, USER_EVENTS} from './user'
import {VENDOR_ACTIONS, VENDOR_COMMANDS, VENDOR_EVENTS} from './vendor'


export const ACTIONS = {
  ...APPLICATION_ACTIONS,
  ...BILLING_MODEL_ACTIONS,
  ...CART_ACTIONS,
  ...COLLECTION_ACTIONS,
  ...COUNTRY_ACTIONS,
  ...CUSTOMER_ACTIONS,
  ...FEED_ACTIONS,
  ...FULFILLMENT_ACTIONS,
  ...GATEWAY_ACTIONS,
  ...OFFER_ACTIONS,
  ...ORDER_ACTIONS,
  ...PERMISSION_ACTIONS,
  ...SUBSCRIPTION_ACTIONS,
  ...TASK_ACTIONS,
  ...TRANSACTION_ACTIONS,
  ...USER_ACTIONS,
  ...VENDOR_ACTIONS
}

export const COMMANDS = {
  ...APPLICATION_COMMANDS,
  ...BILLING_MODEL_COMMANDS,
  ...CART_COMMANDS,
  ...COLLECTION_COMMANDS,
  ...COUNTRY_COMMANDS,
  ...CUSTOMER_COMMANDS,
  ...FEED_COMMANDS,
  ...FULFILLMENT_COMMANDS,
  ...GATEWAY_COMMANDS,
  ...OFFER_COMMANDS,
  ...ORDER_COMMANDS,
  ...PERMISSION_COMMANDS,
  ...SUBSCRIPTION_COMMANDS,
  ...TASK_COMMANDS,
  ...TRANSACTION_COMMANDS,
  ...USER_COMMANDS,
  ...VENDOR_COMMANDS
}

export const EVENTS = {
  ...APPLICATION_EVENTS,
  ...BILLING_MODEL_EVENTS,
  ...COLLECTION_EVENTS,
  ...CART_EVENTS,
  ...COUNTRY_EVENTS,
  ...CUSTOMER_EVENTS,
  ...FEED_EVENTS,
  ...FULFILLMENT_EVENTS,
  ...GATEWAY_EVENTS,
  ...OFFER_EVENTS,
  ...ORDER_EVENTS,
  ...PERMISSION_EVENTS,
  ...SUBSCRIPTION_EVENTS,
  ...TASK_EVENTS,
  ...TRANSACTION_EVENTS,
  ...USER_EVENTS,
  ...VENDOR_EVENTS
}
