export const ORDER_COMMANDS = {
  'CREATE_ORDER': 'create.channel.:channel_uuid.order',
  'UPDATE_ORDER': 'update.channel.:channel_uuid.order.:order_uuid',
  'DESTROY_ORDER': 'destroy.channel.:channel_uuid.order.:order_uuid',
  'PAY_ORDER': 'pay.channel.:channel_uuid.order.:order_uuid',
  'PARTIALLY_PAY_ORDER': 'partially_pay.channel.:channel_uuid.order.:order_uuid',
  'FULFILL_ORDER': 'fulfill.channel.:channel_uuid.order.:order_uuid',
  'PARTIALLY_FULFILL_ORDER': 'partially_fulfill.channel.:channel_uuid.order.:order_uuid',
  'REFUND_ORDER': 'refund.channel.:channel_uuid.order.:order_uuid',
  'PARTIALLY_REFUND_ORDER': 'partially_refund.channel.:channel_uuid.order.:order_uuid',
  'CLOSE_ORDER': 'close.channel.:channel_uuid.order.:order_uuid',
  'CANCEL_ORDER': 'cancel.channel.:channel_uuid.order.:order_uuid',
  'CALCULATE_ORDER': 'calculate.channel.:channel_uuid.order.:order_uuid',
  'SET_ORDER_CUSTOMER': 'set.channel.:channel_uuid.order.:order_uuid.customer',
  'SET_ORDER_BILLING': 'set.channel.:channel_uuid.order.:order_uuid.address_billing',
  'SET_ORDER_SHIPPING': 'set.channel.:channel_uuid.order.:order_uuid.address_shipping',
  'SET_ORDER_PAYMENT': 'set.channel.:channel_uuid.order.:order_uuid.payment_details',
  'SET_ORDER_FULFILLMENT': 'set.channel.:channel_uuid.order.:order_uuid.fulfillment_details',
  'ADD_ORDER_SHIPPING_LINE': 'add.channel.:channel_uuid.order.:order_uuid.lines_shipping',
  'ADD_ORDER_TAX_LINE': 'add.channel.:channel_uuid.order.:order_uuid.lines_taxes',
  'ADD_ORDER_OVERRIDE_LINE': 'add.channel.:channel_uuid.order.:order_uuid.lines_pricing_overrides',
  'REMOVE_ORDER_SHIPPING_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.lines_shipping',
  'REMOVE_ORDER_TAX_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.lines_taxes',
  'REMOVE_ORDER_OVERRIDE_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.lines_pricing_overrides',

  'UPLOAD_ORDERS': 'upload.channel.:channel_uuid.order',
  'PROCESS_UPLOADED_ORDERS': 'process.upload.channel.:channel_uuid.order',

  'CREATE_ORDER_ITEM': 'create.channel.:channel_uuid.order.:order_uuid.item',
  'CREATE_ORDER_ITEMS': 'create.channel.:channel_uuid.order.:order_uuid.list.item',
  'UPDATE_ORDER_ITEM': 'update.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'REMOVE_ORDER_ITEM': 'remove.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'DESTROY_ORDER_ITEM': 'destroy.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'INCREASE_ORDER_ITEM_QUANTITY': 'create.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.quantity.increase',
  'DECREASE_ORDER_ITEM_QUANTITY': 'create.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.quantity.decrease',
  'SET_ORDER_ITEM_PAYMENT': 'set.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.payment_details',
  'SET_ORDER_ITEM_FULFILLMENT': 'set.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.fulfillment_details',
  'ADD_ORDER_ITEM_SHIPPING_LINE': 'add.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_shipping',
  'ADD_ORDER_ITEM_TAX_LINE': 'add.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_taxes',
  'ADD_ORDER_ITEM_OVERRIDE_LINE': 'add.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_pricing_overrides',
  'REMOVE_ORDER_ITEM_SHIPPING_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.item..:item_uuidlines_shipping',
  'REMOVE_ORDER_ITEM_TAX_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_taxes',
  'REMOVE_ORDER_ITEM_OVERRIDE_LINE': 'remove.channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_pricing_overrides',

  'CREATE_ORDER_TRANSACTION': 'create.channel.:channel_uuid.order.:order_uuid.transaction',
  'CREATE_ORDER_TRANSACTIONS': 'create.channel.:channel_uuid.order.:order_uuid.list.transaction',

  'CREATE_ORDER_FULFILLMENT': 'create.channel.:channel_uuid.order.:order_uuid.fulfillment',
  'CREATE_ORDER_FULFILLMENTS': 'create.channel.:channel_uuid.order.:order_uuid.list.fulfillment',

  'AUTHORIZE_ORDER_TRANSACTION': 'authorize.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'PARTIALLY_AUTHORIZE_ORDER_TRANSACTION': 'partially_authorize.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'CAPTURE_ORDER_TRANSACTION': 'capture.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'PARTIALLY_CAPTURE_ORDER_TRANSACTION': 'partially_capture.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'VOID_ORDER_TRANSACTION': 'void.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'REFUND_ORDER_TRANSACTION': 'refund.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'PARTIALLY_REFUND_ORDER_TRANSACTION': 'partially_refund.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'SALE_ORDER_TRANSACTION': 'sale.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'PARTIALLY_SALE_ORDER_TRANSACTION': 'partially_sale.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',
  'CANCEL_ORDER_TRANSACTION': 'cancel.channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid',

  'FULFILL_ORDER_ITEM': 'fulfill.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'FULFILL_ORDER_ITEMS': 'fulfill.channel.:channel_uuid.order.:order_uuid.list.item',
  'RETURN_ORDER_ITEM': 'return.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'RETURN_ORDER_ITEMS': 'return.channel.:channel_uuid.order.:order_uuid.list.item',
  'RESTOCK_ORDER_ITEM': 'restock.channel.:channel_uuid.order.:order_uuid.item.:item_uuid',
  'RESTOCK_ORDER_ITEMS': 'restock.channel.:channel_uuid.order.:order_uuid.list.item',
}
export const ORDER_ACTIONS = {
  'GET_ORDER': 'channel.order.get',
  'LIST_ORDERS': 'channel.order.list',
  'GET_ORDER_CUSTOMER': 'channel.order.customer.get',
  'GET_ORDER_TRANSACTION': 'channel.order.transaction.get',
  'LIST_ORDER_TRANSACTIONS': 'channel.order.transaction.list',
  'LIST_ORDER_TRANSACTION_EVENTS': 'channel.order.transaction.event.list',
  'GET_ORDER_FULFILLMENT': 'channel.order.fulfillment.get',
  'LIST_ORDER_FULFILLMENTS': 'channel.order.fulfillment.list',
  'LIST_ORDER_FULFILLMENT_EVENTS': 'channel.order.fulfillment.event.list',
  'LIST_ORDER_EVENTS': 'channel.order.event.list',
  'GET_ORDER_BILLING': 'channel.order.address_billing.get',
  'GET_ORDER_SHIPPING': 'channel.order.address_shipping.get',
  'GET_ORDER_PAYMENT_DETAILS': 'channel.order.payment_details.get',
  'GET_ORDER_FULFILLMENT_DETAILS': 'channel.order.fulfillment_details.get',
  'LIST_ORDER_SHIPPING_LINES': 'channel.order.lines_shipping.list',
  'LIST_ORDER_TAX_LINES': 'channel.order.lines_taxes.list',
  'LIST_ORDER_OVERRIDE_LINES': 'channel.order.lines_pricing_overrides.list',

  'GET_ORDER_ITEM': 'channel.order.item.get',
  'LIST_ORDER_ITEMS': 'channel.order.item.list',
  'GET_ORDER_ITEM_PAYMENT_DETAILS': 'channel.order.item.payment_details.get',
  'GET_ORDER_ITEM_FULFILLMENT_DETAILS': 'channel.order.item.fulfillment_details.get',
  'LIST_ORDER_ITEM_SHIPPING_LINES': 'channel.order.item.lines_shipping.list',
  'LIST_ORDER_ITEM_TAX_LINES': 'channel.order.item.lines_taxes.list',
  'LIST_ORDER_ITEM_OVERRIDE_LINES': 'channel.order.item.lines_pricing_overrides.list',

  'GET_ORDER_UPLOAD': 'channel.order.upload.get',
  'LIST_ORDER_UPLOADS': 'channel.order.upload.list',
}
export const ORDER_EVENTS = {
  'ORDER_CREATED': 'channel.:channel_uuid.order.:order_uuid.created',
  'ORDER_UPDATED': 'channel.:channel_uuid.order.:order_uuid.updated',
  'ORDER_DESTROYED': 'channel.:channel_uuid.order.:order_uuid.destroyed',
  'ORDER_PAID': 'channel.:channel_uuid.order.:order_uuid.paid',
  'ORDER_PARTIALLY_PAID': 'channel.:channel_uuid.order.:order_uuid.partially_paid',
  'ORDER_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.fulfilled',
  'ORDER_PARTIALLY_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.partially_fulfilled',
  'ORDER_REFUNDED': 'channel.:channel_uuid.order.:order_uuid.refunded',
  'ORDER_PARTIALLY_REFUNDED': 'channel.:channel_uuid.order.:order_uuid.partially_refunded',
  'ORDER_CLOSED': 'channel.:channel_uuid.order.:order_uuid.closed',
  'ORDER_CANCELLED': 'channel.:channel_uuid.order.:order_uuid.cancelled',
  'ORDER_CUSTOMER_SET': 'channel.:channel_uuid.order.:order_uuid.customer.set',
  'ORDER_BILLING_SET': 'channel.:channel_uuid.order.:order_uuid.address_billing.set',
  'ORDER_SHIPPING_SET': 'channel.:channel_uuid.order.:order_uuid.address_shipping.set',
  'ORDER_PAYMENT_SET': 'channel.:channel_uuid.order.:order_uuid.payment_details.set',
  'ORDER_FULFILLMENT_SET': 'channel.:channel_uuid.order.:order_uuid.fulfillment_details.set',
  'ORDER_SHIPPING_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.lines_shipping.added',
  'ORDER_TAX_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.lines_taxes.added',
  'ORDER_OVERRIDE_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.lines_pricing_overrides.added',
  'ORDER_SHIPPING_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.lines_shipping.removed',
  'ORDER_TAX_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.lines_taxes.removed',
  'ORDER_OVERRIDE_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.lines_pricing_overrides.removed',
  'ORDER_CALCULATED': 'channel.:channel_uuid.order.:order_uuid.calculated',

  'ORDERS_UPLOADED': 'channel.:channel_uuid.order.uploaded.list',
  'ORDERS_UPLOAD_PROCESSED': 'channel.:channel_uuid.order.upload.processed.list',

  'ORDER_ITEM_CREATED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.created',
  'ORDER_ITEMS_CREATED': 'channel.:channel_uuid.order.:order_uuid.item.created.list',
  'ORDER_ITEM_UPDATED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.updated',
  'ORDER_ITEM_QUANTITY_INCREASED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.quantity.increased',
  'ORDER_ITEM_QUANTITY_DECREASED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.quantity.decreased',
  'ORDER_ITEM_REMOVED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.removed',
  'ORDER_ITEM_DESTROYED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.destroyed',
  'ORDER_ITEM_PAYMENT_SET': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.payment_details.set',
  'ORDER_ITEM_FULFILLMENT_SET': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.fulfillment_details.set',
  'ORDER_ITEM_SHIPPING_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_shipping.added',
  'ORDER_ITEM_TAX_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_taxes.added',
  'ORDER_ITEM_OVERRIDE_LINE_ADDED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_pricing_overrides.added',
  'ORDER_ITEM_SHIPPING_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_shipping.removed',
  'ORDER_ITEM_TAX_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_taxes.removed',
  'ORDER_ITEM_OVERRIDE_LINE_REMOVED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.lines_pricing_overrides.removed',

  'ORDER_ITEM_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.fulfilled',
  'ORDER_ITEMS_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.item.fulfilled.list',
  'ORDER_ITEM_RETURNED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.returned',
  'ORDER_ITEMS_RETURNED': 'channel.:channel_uuid.order.:order_uuid.item.returned.list',
  'ORDER_ITEM_RESTOCKED': 'channel.:channel_uuid.order.:order_uuid.item.:item_uuid.restocked',
  'ORDER_ITEMS_RESTOCKED': 'channel.:channel_uuid.order.:order_uuid.item.restocked.list',

  'ORDER_FULFILLMENT_CREATED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.created',
  'ORDER_FULFILLMENTS_CREATED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.created.list',

  'ORDER_FULFILLMENT_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.fulfilled',
  'ORDER_FULFILLMENT_PARTIALLY_FULFILLED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.partially_fulfilled',
  'ORDER_FULFILLMENT_RETURNED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.returned',
  'ORDER_FULFILLMENT_PARTIALLY_RETURNED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.partially_returned',
  'ORDER_FULFILLMENT_RESTOCKED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.restocked',
  'ORDER_FULFILLMENT_PARTIALLY_RESTOCKED': 'channel.:channel_uuid.order.:order_uuid.fulfillment.:fulfillment_uuid.partially_restocked',

  'ORDER_TRANSACTION_SOLD': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.sold',
  'ORDER_TRANSACTION_PARTIALLY_SOLD': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.partially_sold',
  'ORDER_TRANSACTION_AUTHORIZED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.authorized',
  'ORDER_TRANSACTION_PARTIALLY_AUTHORIZED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.partially_authorized',
  'ORDER_TRANSACTION_REFUNDED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.refunded',
  'ORDER_TRANSACTION_PARTIALLY_REFUNDED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.partially_refunded',
  'ORDER_TRANSACTION_CAPTURED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.captured',
  'ORDER_TRANSACTION_PARTIALLY_CAPTURED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.partially_captured',
  'ORDER_TRANSACTION_CANCELLED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.cancelled',
  'ORDER_TRANSACTION_VOIDED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.voided',
  'ORDER_TRANSACTION_CALCULATED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.calculated',
  'ORDER_TRANSACTION_CREATED': 'channel.:channel_uuid.order.:order_uuid.transaction.:transaction_uuid.created',
  'ORDER_TRANSACTIONS_CREATED': 'channel.:channel_uuid.order.:order_uuid.transaction.created.list',
}
