export const ORDER_COMMANDS = {
  'CREATE_ORDER': 'create.channel.order',
  'UPDATE_ORDER': 'update.channel.order',
  'DESTROY_ORDER': 'destroy.channel.order',

  'UPLOAD_ORDERS': 'upload.channel.order',
  'PROCESS_UPLOADED_ORDERS': 'process.upload.channel.order',

  'PAY_ORDER': 'pay.channel.order',
  'PARTIALLY_PAY_ORDER': 'partially_pay.channel.order',
  'FULFILL_ORDER': 'fulfill.channel.order',
  'PARTIALLY_FULFILL_ORDER': 'partially_fulfill.channel.order',
  'REFUND_ORDER': 'refund.channel.order',
  'PARTIALLY_REFUND_ORDER': 'partially_refund.channel.order',
  'CLOSE_ORDER': 'close.channel.order',
  'CANCEL_ORDER': 'cancel.channel.order',
  'SET_ORDER_CUSTOMER': 'set.channel.order.customer',
  'SET_ORDER_BILLING': 'set.channel.order.address_billing',
  'SET_ORDER_SHIPPING': 'set.channel.order.address_shipping',
  'SET_ORDER_PAYMENT': 'set.channel.order.payment_details',
  'SET_ORDER_FULFILLMENT': 'set.channel.order.fulfillment_details',
  'ADD_ORDER_SHIPPING_LINE': 'add.channel.order.lines_shipping',
  'ADD_ORDER_TAX_LINE': 'add.channel.order.lines_taxes',
  'ADD_ORDER_OVERRIDE_LINE': 'add.channel.order.lines_pricing_overrides',
  'REMOVE_ORDER_SHIPPING_LINE': 'remove.channel.order.lines_shipping',
  'REMOVE_ORDER_TAX_LINE': 'remove.channel.order.lines_taxes',
  'REMOVE_ORDER_OVERRIDE_LINE': 'remove.channel.order.lines_pricing_overrides',
  'CALCULATE_ORDER': 'calculate.channel.order',

  'CREATE_ORDER_ITEM': 'create.channel.order.item',
  'CREATE_ORDER_ITEMS': 'create.channel.order.item.list',
  'UPDATE_ORDER_ITEM': 'update.channel.order.item',
  'REMOVE_ORDER_ITEM': 'remove.channel.order.item',
  'DESTROY_ORDER_ITEM': 'destroy.channel.order.item',
  'INCREASE_ORDER_ITEM_QUANTITY': 'create.channel.order.item.quantity.increase',
  'DECREASE_ORDER_ITEM_QUANTITY': 'create.channel.order.item.quantity.decrease',
  'SET_ORDER_ITEM_PAYMENT': 'set.channel.order.item.payment_details',
  'SET_ORDER_ITEM_FULFILLMENT': 'set.channel.order.item.fulfillment_details',
  'ADD_ORDER_ITEM_SHIPPING_LINE': 'add.channel.order.item.lines_shipping',
  'ADD_ORDER_ITEM_TAX_LINE': 'add.channel.order.item.lines_taxes',
  'ADD_ORDER_ITEM_OVERRIDE_LINE': 'add.channel.order.item.lines_pricing_overrides',
  'REMOVE_ORDER_ITEM_SHIPPING_LINE': 'remove.channel.order.item.lines_shipping',
  'REMOVE_ORDER_ITEM_TAX_LINE': 'remove.channel.order.item.lines_taxes',
  'REMOVE_ORDER_ITEM_OVERRIDE_LINE': 'remove.channel.order.item.lines_pricing_overrides',

  'CREATE_ORDER_TRANSACTION': 'create.channel.order.transaction',
  'CREATE_ORDER_TRANSACTIONS': 'create.channel.order.transaction.list',

  'CREATE_ORDER_FULFILLMENT': 'create.channel.order.fulfillment',
  'CREATE_ORDER_FULFILLMENTS': 'create.channel.order.fulfillment.list',

  'AUTHORIZE_ORDER_TRANSACTION': 'authorize.channel.order.transaction',
  'PARTIALLY_AUTHORIZE_ORDER_TRANSACTION': 'partially_authorize.channel.order.transaction',
  'CAPTURE_ORDER_TRANSACTION': 'capture.channel.order.transaction',
  'PARTIALLY_CAPTURE_ORDER_TRANSACTION': 'partially_capture.channel.order.transaction',
  'VOID_ORDER_TRANSACTION': 'void.channel.order.transaction',
  'REFUND_ORDER_TRANSACTION': 'refund.channel.order.transaction',
  'PARTIALLY_REFUND_ORDER_TRANSACTION': 'partially_refund.channel.order.transaction',
  'SALE_ORDER_TRANSACTION': 'sale.channel.order.transaction',
  'PARTIALLY_SALE_ORDER_TRANSACTION': 'partially_sale.channel.order.transaction',
  'CANCEL_ORDER_TRANSACTION': 'cancel.channel.order.transaction',

  'FULFILL_ORDER_ITEM': 'fulfill.channel.order.item',
  'FULFILL_ORDER_ITEMS': 'fulfill.channel.order.item.list',
  'RETURN_ORDER_ITEM': 'return.channel.order.item',
  'RETURN_ORDER_ITEMS': 'return.channel.order.item.list',
  'RESTOCK_ORDER_ITEM': 'restock.channel.order.item',
  'RESTOCK_ORDER_ITEMS': 'restock.channel.order.item.list',
}
export const ORDER_ACTIONS = {
  'GET_ORDER': 'channel.order.get',
  'LIST_ORDERS': 'channel.order.list',
  'GET_ORDER_CUSTOMER': 'channel.order.customer.get',
  'GET_ORDER_TRANSACTION': 'channel.order.transaction.get',
  'LIST_ORDER_TRANSACTIONS': 'channel.order.transaction.list',
  'LIST_ORDER_TRANSACTION_EVENTS': 'channel.order.transaction.event.list',
  'GET_ORDER_FULFILLMENT': 'channel.order.fulfillment.get',
  'LIST_ORDER_FULFILLMENTS': 'channel.order.fulfillment.list',
  'LIST_ORDER_FULFILLMENT_EVENTS': 'channel.order.fulfillment.event.list',
  'LIST_ORDER_EVENTS': 'channel.order.event.list',
  'GET_ORDER_BILLING': 'channel.order.address_billing.get',
  'GET_ORDER_SHIPPING': 'channel.order.address_shipping.get',
  'GET_ORDER_PAYMENT_DETAILS': 'channel.order.payment_details.get',
  'GET_ORDER_FULFILLMENT_DETAILS': 'channel.order.fulfillment_details.get',
  'LIST_ORDER_SHIPPING_LINES': 'channel.order.lines_shipping.list',
  'LIST_ORDER_TAX_LINES': 'channel.order.lines_taxes.list',
  'LIST_ORDER_OVERRIDE_LINES': 'channel.order.lines_pricing_overrides.list',

  'GET_ORDER_ITEM': 'channel.order.item.get',
  'LIST_ORDER_ITEMS': 'channel.order.item.list',
  'GET_ORDER_ITEM_PAYMENT_DETAILS': 'channel.order.item.payment_details.get',
  'GET_ORDER_ITEM_FULFILLMENT_DETAILS': 'channel.order.item.fulfillment_details.get',
  'LIST_ORDER_ITEM_SHIPPING_LINES': 'channel.order.item.lines_shipping.list',
  'LIST_ORDER_ITEM_TAX_LINES': 'channel.order.item.lines_taxes.list',
  'LIST_ORDER_ITEM_OVERRIDE_LINES': 'channel.order.item.lines_pricing_overrides.list',

  'GET_ORDER_UPLOAD': 'channel.order.upload.get',
  'LIST_ORDER_UPLOADS': 'channel.order.upload.list',
}
export const ORDER_EVENTS = {
  'ORDER_CREATED': 'channel.order.created',
  'ORDER_UPDATED': 'channel.order.updated',
  'ORDER_DESTROYED': 'channel.order.destroyed',
  'ORDERS_UPLOADED': 'channel.order.uploaded.list',
  'ORDERS_UPLOAD_PROCESSED': 'channel.order.upload.processed.list',
  'ORDER_ITEM_CREATED': 'channel.order.item.created',
  'ORDER_ITEMS_CREATED': 'channel.order.item.created.list',
  'ORDER_ITEM_UPDATED': 'channel.order.item.updated',
  'ORDER_ITEM_QUANTITY_INCREASED': 'channel.order.item.quantity.increased',
  'ORDER_ITEM_QUANTITY_DECREASED': 'channel.order.item.quantity.decreased',
  'ORDER_ITEM_REMOVED': 'channel.order.item.removed',
  'ORDER_ITEM_DESTROYED': 'channel.order.item.destroyed',
  'ORDER_ITEM_PAYMENT_SET': 'channel.order.item.payment_details.set',
  'ORDER_ITEM_FULFILLMENT_SET': 'channel.order.item.fulfillment_details.set',
  'ORDER_ITEM_SHIPPING_LINE_ADDED': 'channel.order.item.lines_shipping.added',
  'ORDER_ITEM_TAX_LINE_ADDED': 'channel.order.item.lines_taxes.added',
  'ORDER_ITEM_OVERRIDE_LINE_ADDED': 'channel.order.item.lines_pricing_overrides.added',
  'ORDER_ITEM_SHIPPING_LINE_REMOVED': 'channel.order.item.lines_shipping.removed',
  'ORDER_ITEM_TAX_LINE_REMOVED': 'channel.order.item.lines_taxes.removed',
  'ORDER_ITEM_OVERRIDE_LINE_REMOVED': 'channel.order.item.lines_pricing_overrides.removed',

  'ORDER_ITEM_FULFILLED': 'channel.order.item.fulfilled',
  'ORDER_ITEMS_FULFILLED': 'channel.order.item.fulfilled.list',
  'ORDER_ITEM_RETURNED': 'channel.order.item.returned',
  'ORDER_ITEMS_RETURNED': 'channel.order.item.returned.list',
  'ORDER_ITEM_RESTOCKED': 'channel.order.item.restocked',
  'ORDER_ITEMS_RESTOCKED': 'channel.order.item.restocked.list',

  'ORDER_PAID': 'channel.order.paid',
  'ORDER_PARTIALLY_PAID': 'channel.order.partially_paid',
  'ORDER_FULFILLED': 'channel.order.fulfilled',
  'ORDER_PARTIALLY_FULFILLED': 'channel.order.partially_fulfilled',
  'ORDER_REFUNDED': 'channel.order.refunded',
  'ORDER_PARTIALLY_REFUNDED': 'channel.order.partially_refunded',
  'ORDER_CLOSED': 'channel.order.closed',
  'ORDER_CANCELLED': 'channel.order.cancelled',
  'ORDER_CUSTOMER_SET': 'channel.order.customer.set',
  'ORDER_BILLING_SET': 'channel.order.address_billing.set',
  'ORDER_SHIPPING_SET': 'channel.order.address_shipping.set',
  'ORDER_PAYMENT_SET': 'channel.order.payment_details.set',
  'ORDER_FULFILLMENT_SET': 'channel.order.fulfillment_details.set',
  'ORDER_SHIPPING_LINE_ADDED': 'channel.order.lines_shipping.added',
  'ORDER_TAX_LINE_ADDED': 'channel.order.lines_taxes.added',
  'ORDER_OVERRIDE_LINE_ADDED': 'channel.order.lines_pricing_overrides.added',
  'ORDER_SHIPPING_LINE_REMOVED': 'channel.order.lines_shipping.removed',
  'ORDER_TAX_LINE_REMOVED': 'channel.order.lines_taxes.removed',
  'ORDER_OVERRIDE_LINE_REMOVED': 'channel.order.lines_pricing_overrides.removed',
  'ORDER_CALCULATED': 'channel.order.calculated',

  'ORDER_TRANSACTION_SOLD': 'channel.order.transaction.sold',
  'ORDER_TRANSACTION_PARTIALLY_SOLD': 'channel.order.transaction.partially_sold',
  'ORDER_TRANSACTION_AUTHORIZED': 'channel.order.transaction.authorized',
  'ORDER_TRANSACTION_PARTIALLY_AUTHORIZED': 'channel.order.transaction.partially_authorized',
  'ORDER_TRANSACTION_REFUNDED': 'channel.order.transaction.refunded',
  'ORDER_TRANSACTION_PARTIALLY_REFUNDED': 'channel.order.transaction.partially_refunded',
  'ORDER_TRANSACTION_CAPTURED': 'channel.order.transaction.captured',
  'ORDER_TRANSACTION_PARTIALLY_CAPTURED': 'channel.order.transaction.partially_captured',
  'ORDER_TRANSACTION_CANCELLED': 'channel.order.transaction.cancelled',
  'ORDER_TRANSACTION_VOIDED': 'channel.order.transaction.voided',
  'ORDER_TRANSACTION_CALCULATED': 'channel.order.transaction.calculated',


  'ORDER_TRANSACTION_CREATED': 'channel.order.transaction.created',
  'ORDER_TRANSACTIONS_CREATED': 'channel.order.transaction.created.list',

  'ORDER_FULFILLMENT_CREATED': 'channel.order.fulfillment.created',
  'ORDER_FULFILLMENTS_CREATED': 'channel.order.fulfillment.created.list',
}
