export const PRODUCT_COMMANDS = {
  'CREATE_PRODUCT': 'create.channel.:channel_uuid.product',
  'MERGE_PRODUCTS': 'merge.channel.:channel_uuid.list.product',
  'ADD_PRODUCT': 'add.channel.:channel_uuid.product.:product_uuid',
  'ADD_PRODUCTS': 'add.channel.:channel_uuid.list.product',
  'UPDATE_PRODUCT': 'update.channel.:channel_uuid.product.:product_uuid',
  'DESTROY_PRODUCT': 'destroy.channel.:channel_uuid.product.:product_uuid',
  'REMOVE_PRODUCT': 'remove.channel.:channel_uuid.product.:product_uuid',
  'PUBLISH_PRODUCT': 'publish.channel.:channel_uuid.product.:product_uuid',
  'UNPUBLISH_PRODUCT': 'unpublish.channel.:channel_uuid.product.:product_uuid',
  'PUBLISH_PRODUCTS': 'publish.channel.:channel_uuid.list.product.:product_uuid',
  'UNPUBLISH_PRODUCTS': 'unpublish.channel.:channel_uuid.list.product.:product_uuid',
  'SET_PRODUCT_IMAGE_PRIMARY': 'set.channel.:channel_uuid.product.:product_uuid.image_primary',
  'SET_PRODUCT_VARIANT_DEFAULT': 'set.channel.:channel_uuid.product.:product_uuid.variant_default',

  'ADD_PRODUCT_CATEGORY': 'add.channel.:channel_uuid.product.:product_uuid.category',
  'REMOVE_PRODUCT_CATEGORY': 'remove.channel.:channel_uuid.product.:product_uuid.category',

  'UPLOAD_PRODUCTS': 'upload.channel.:channel_uuid.list.product',
  'PROCESS_UPLOADED_PRODUCTS': 'process.channel.:channel_uuid.upload.:upload_uuid.list.product',
  'UPLOAD_PRODUCT_METADATA': 'upload.channel.:channel_uuid.product.list.metadata',
  'PROCESS_UPLOADED_PRODUCT_METADATA': 'process.channel.:channel_uuid.product.upload.:upload_uuid.list.metadata',
  'UPLOAD_PRODUCT_VARIANTS': 'upload.channel.:channel_uuid.product.list.variant',
  'PROCESS_UPLOADED_PRODUCT_VARIANTS': 'process.channel.:channel_uuid.product.upload.:upload_uuid.list.variant',

  'ADD_PRODUCT_ASSOCIATION': 'add.channel.:channel_uuid.product.:product_uuid.association',
  'ADD_PRODUCT_ASSOCIATIONS': 'add.channel.:channel_uuid.product.:product_uuid.list.association',
  'CREATE_PRODUCT_ASSOCIATION': 'create.channel.:channel_uuid.product.:product_uuid.association',
  'CREATE_PRODUCT_ASSOCIATIONS': 'create.channel.:channel_uuid.product.:product_uuid.list.association',
  'UPDATE_PRODUCT_ASSOCIATION': 'update.channel.:channel_uuid.product.:product_uuid.association',
  'REMOVE_PRODUCT_ASSOCIATION': 'remove.channel.:channel_uuid.product.:product_uuid.association',
  'DESTROY_PRODUCT_ASSOCIATION': 'destroy.channel.:channel_uuid.product.:product_uuid.association',
  'PUBLISH_PRODUCT_ASSOCIATION': 'publish.channel.:channel_uuid.product.:product_uuid.association',
  'UNPUBLISH_PRODUCT_ASSOCIATION': 'unpublish.channel.:channel_uuid.product.:product_uuid.association',

  'ADD_PRODUCT_IMAGE': 'add.channel.:channel_uuid.product.:product_uuid.image',
  'ADD_PRODUCT_IMAGES': 'add.channel.:channel_uuid.product.:product_uuid.list.image',
  'CREATE_PRODUCT_IMAGE': 'create.channel.:channel_uuid.product.:product_uuid.image',
  'CREATE_PRODUCT_IMAGES': 'create.channel.:channel_uuid.product.:product_uuid.list.image',
  'UPDATE_PRODUCT_IMAGE': 'update.channel.:channel_uuid.product.:product_uuid.image',
  'REMOVE_PRODUCT_IMAGE': 'remove.channel.:channel_uuid.product.:product_uuid.image',
  'DESTROY_PRODUCT_IMAGE': 'destroy.channel.:channel_uuid.product.:product_uuid.image',
  'PUBLISH_PRODUCT_IMAGE': 'publish.channel.:channel_uuid.product.:product_uuid.image',
  'UNPUBLISH_PRODUCT_IMAGE': 'unpublish.channel.:channel_uuid.product.:product_uuid.image',

  'ADD_PRODUCT_VARIANT': 'add.channel.:channel_uuid.product.:product_uuid.variant',
  'ADD_PRODUCT_VARIANTS': 'add.channel.:channel_uuid.product.:product_uuid.list.variant',
  'CREATE_PRODUCT_VARIANT': 'create.channel.:channel_uuid.product.:product_uuid.variant',
  'CREATE_PRODUCT_VARIANTS': 'create.channel.:channel_uuid.product.:product_uuid.list.variant',
  'UPDATE_PRODUCT_VARIANT': 'update.channel.:channel_uuid.product.:product_uuid.variant',
  'REMOVE_PRODUCT_VARIANT': 'remove.channel.:channel_uuid.product.:product_uuid.variant',
  'DESTROY_PRODUCT_VARIANT': 'destroy.channel.:channel_uuid.product.:product_uuid.variant',
  'PUBLISH_PRODUCT_VARIANT': 'publish.channel.:channel_uuid.product.:product_uuid.variant',
  'UNPUBLISH_PRODUCT_VARIANT': 'unpublish.channel.:channel_uuid.product.:product_uuid.variant',
  'PUBLISH_PRODUCT_VARIANTS': 'publish.channel.:channel_uuid.product.:product_uuid.list.variant',
  'UNPUBLISH_PRODUCT_VARIANTS': 'unpublish.channel.:channel_uuid.product.:product_uuid.list.variant',


  'ADD_PRODUCT_VARIANT_ASSOCIATION': 'add.channel.:channel_uuid.product.:product_uuid.variant.association',
  'ADD_PRODUCT_VARIANT_ASSOCIATIONS': 'add.channel.:channel_uuid.product.:product_uuid.variant.list.association',
  'CREATE_PRODUCT_VARIANT_ASSOCIATION': 'create.channel.:channel_uuid.product.:product_uuid.variant.association',
  'CREATE_PRODUCT_VARIANT_ASSOCIATIONS': 'create.channel.:channel_uuid.product.:product_uuid.variant.list.association',
  'UPDATE_PRODUCT_VARIANT_ASSOCIATION': 'update.channel.:channel_uuid.product.:product_uuid.variant.association',
  'REMOVE_PRODUCT_VARIANT_ASSOCIATION': 'remove.channel.:channel_uuid.product.:product_uuid.variant.association',
  'DESTROY_PRODUCT_VARIANT_ASSOCIATION': 'destroy.channel.:channel_uuid.product.:product_uuid.variant.association',
  'PUBLISH_PRODUCT_VARIANT_ASSOCIATION': 'publish.channel.:channel_uuid.product.:product_uuid.variant.association',
  'UNPUBLISH_PRODUCT_VARIANT_ASSOCIATION': 'unpublish.channel.:channel_uuid.product.:product_uuid.variant.association',

  'ADD_PRODUCT_VARIANT_IMAGE': 'add.channel.:channel_uuid.product.:product_uuid.variant.image',
  'ADD_PRODUCT_VARIANT_IMAGES': 'add.channel.:channel_uuid.product.:product_uuid.variant.list.image',
  'CREATE_PRODUCT_VARIANT_IMAGE': 'create.channel.:channel_uuid.product.:product_uuid.variant.image',
  'CREATE_PRODUCT_VARIANT_IMAGES': 'create.channel.:channel_uuid.product.:product_uuid.variant.list.image',
  'UPDATE_PRODUCT_VARIANT_IMAGE': 'update.channel.:channel_uuid.product.:product_uuid.variant.image',
  'REMOVE_PRODUCT_VARIANT_IMAGE': 'remove.channel.:channel_uuid.product.:product_uuid.variant.image',
  'DESTROY_PRODUCT_VARIANT_IMAGE': 'destroy.channel.:channel_uuid.product.:product_uuid.variant.image',
  'PUBLISH_PRODUCT_VARIANT_IMAGE': 'publish.channel.:channel_uuid.product.:product_uuid.variant.image',
  'UNPUBLISH_PRODUCT_VARIANT_IMAGE': 'unpublish.channel.:channel_uuid.product.:product_uuid.variant.image',


  'ADD_PRODUCT_VENDOR': 'add.channel.:channel_uuid.product.:product_uuid.vendor',
  'ADD_PRODUCT_VENDORS': 'add.channel.:channel_uuid.product.:product_uuid.list.vendor',
  'CREATE_PRODUCT_VENDOR': 'create.channel.:channel_uuid.product.:product_uuid.vendor',
  'CREATE_PRODUCT_VENDORS': 'create.channel.:channel_uuid.product.:product_uuid.list.vendor',
  'UPDATE_PRODUCT_VENDOR': 'update.channel.:channel_uuid.product.:product_uuid.vendor',
  'REMOVE_PRODUCT_VENDOR': 'remove.channel.:channel_uuid.product.:product_uuid.vendor',
  'DESTROY_PRODUCT_VENDOR': 'destroy.channel.:channel_uuid.product.:product_uuid.vendor',
  'PUBLISH_PRODUCT_VENDOR': 'publish.channel.:channel_uuid.product.:product_uuid.vendor',
  'UNPUBLISH_PRODUCT_VENDOR': 'unpublish.channel.:channel_uuid.product.:product_uuid.vendor',
  'PUBLISH_PRODUCT_VENDORS': 'publish.channel.:channel_uuid.product.:product_uuid.list.vendor',
  'UNPUBLISH_PRODUCT_VENDORS': 'unpublish.channel.:channel_uuid.product.:product_uuid.list.vendor',
}
export const PRODUCT_ACTIONS = {
  'GET_PRODUCT': 'channel.product.get',
  'FIND_PRODUCT': 'channel.product.get', // ALIAS
  'LIST_PRODUCTS': 'channel.product.list',
  'FIND_PRODUCTS': 'channel.product.list', // ALIAS
  'LIST_PRODUCT_EVENTS': 'channel.product.event.list',

  'GET_PRODUCT_CATEGORY': 'channel.product.category.get',
  'LIST_PRODUCT_CATEGORIES': 'channel.product.category.list',

  'GET_PUBLIC_PRODUCT_CATEGORY': 'channel.public.product.category.get',
  'LIST_PUBLIC_PRODUCT_CATEGORIES': 'channel.public.product.category.list',

  'GET_PRODUCT_UPLOAD_RESULT': 'channel.product.upload_result.get',
  'LIST_PRODUCT_UPLOAD_RESULTS': 'channel.product.upload_result.list',
  'GET_PRODUCT_UPLOAD': 'channel.product.upload.get',
  'LIST_PRODUCT_UPLOADS': 'channel.product.upload.list',

  'GET_PRODUCT_METADATA_UPLOAD_RESULT': 'channel.product.metadata.upload_result.get',
  'LIST_PRODUCT_METADATA_UPLOAD_RESULTS': 'channel.product.metadata.upload_result.list',
  'GET_PRODUCT_METADATA_UPLOAD': 'channel.product.metadata.upload.get',
  'LIST_PRODUCT_METADATA_UPLOADS': 'channel.product.metadata.upload.list',

  'GET_PUBLIC_PRODUCT': 'channel.public.product.get',
  'FIND_PUBLIC_PRODUCT': 'channel.public.product.get', // ALIAS
  'LIST_PUBLIC_PRODUCTS': 'channel.public.product.list',
  'FIND_PUBLIC_PRODUCTS': 'channel.public.product.list', // ALIAS

  'GET_PRODUCT_ASSOCIATION': 'channel.product.association.get',
  'LIST_PRODUCT_ASSOCIATIONS': 'channel.product.association.list',

  'GET_PUBLIC_PRODUCT_ASSOCIATION': 'channel.public.product.association.get',
  'LIST_PUBLIC_PRODUCT_ASSOCIATIONS': 'channel.public.product.association.list',

  'GET_PRODUCT_VARIANT_DEFAULT': 'channel.product.variant.default.get',
  'GET_PRODUCT_VARIANT': 'channel.product.variant.get',
  'LIST_PRODUCT_VARIANTS': 'channel.product.variant.list',
  'FIND_PRODUCT_VARIANTS': 'channel.product.variant.list', // ALIAS

  'GET_PUBLIC_PRODUCT_VARIANT': 'channel.public.product.variant.get',
  'FIND_PUBLIC_PRODUCT_VARIANTS': 'channel.public.product.variant.list', // ALIAS
  'LIST_PUBLIC_PRODUCT_VARIANTS': 'channel.public.product.variant.list',

  'GET_PRODUCT_VARIANT_ASSOCIATION': 'channel.product.variant.association.get',
  'LIST_PRODUCT_VARIANT_ASSOCIATIONS': 'channel.product.variant.association.list',

  'GET_PUBLIC_PRODUCT_VARIANT_ASSOCIATION': 'channel.public.product.variant.association.get',
  'LIST_PUBLIC_PRODUCT_VARIANT_ASSOCIATIONS': 'channel.public.product.variant.association.list',

  'GET_PRODUCT_IMAGE_PRIMARY': 'channel.product.image.primary.get',
  'GET_PRODUCT_IMAGE': 'channel.product.image.get',
  'LIST_PRODUCT_IMAGES': 'channel.product.image.list',

  'GET_PUBLIC_PRODUCT_IMAGE': 'channel.public.product.image.get',
  'LIST_PUBLIC_PRODUCT_IMAGES': 'channel.public.product.image.list',

  'GET_PRODUCT_VARIANT_IMAGE': 'channel.product.variant.image.get',
  'LIST_PRODUCT_VARIANT_IMAGES': 'channel.product.variant.image.list',

  'GET_PUBLIC_PRODUCT_VARIANT_IMAGE': 'channel.public.product.variant.image.get',
  'LIST_PUBLIC_PRODUCT_VARIANT_IMAGES': 'channel.public.product.variant.image.list',

  'GET_PRODUCT_OFFER': 'channel.product.offer.get',
  'LIST_PRODUCT_OFFERS': 'channel.product.offer.list',

  'GET_PRODUCT_VENDOR': 'channel.product.vendor.get',
  'LIST_PRODUCT_VENDORS': 'channel.product.vendor.list',
}
export const PRODUCT_EVENTS = {
  'PRODUCT_CREATED': 'channel.:channel_uuid.product.:product_uuid.created',
  'PRODUCTS_MERGED': 'channel.:channel_uuid.product.merged.list',
  'PRODUCT_ADDED': 'channel.:channel_uuid.product.:product_uuid.added',
  'PRODUCTS_ADDED': 'channel.:channel_uuid.product.:product_uuid.added.list',
  'PRODUCT_UPDATED': 'channel.:channel_uuid.product.:product_uuid.updated',
  'PRODUCT_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.destroyed',

  'PRODUCT_REMOVED': 'channel.:channel_uuid.product.:product_uuid.removed',
  'PRODUCT_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.published',
  'PRODUCT_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.unpublished',
  'PRODUCTS_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.published.list',
  'PRODUCTS_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.unpublished.list',

  'PRODUCT_IMAGE_PRIMARY_SET': 'channel.:channel_uuid.product.:product_uuid.image_primary.set',
  'PRODUCT_VARIANT_DEFAULT_SET': 'channel.:channel_uuid.product.:product_uuid.variant_default.set',

  'PRODUCTS_UPLOADED': 'channel.:channel_uuid.product.uploaded.list',
  'PRODUCTS_UPLOAD_PROCESSED': 'channel.:channel_uuid.product.upload.processed.list',
  'PRODUCTS_METADATA_UPLOADED': 'channel.:channel_uuid.product.metadata.uploaded.list',
  'PRODUCTS_METADATA_UPLOAD_PROCESSED': 'channel.:channel_uuid.product.metadata.upload.processed.list',
  'PRODUCT_ASSOCIATIONS_UPLOADED': 'channel.:channel_uuid.product.association.uploaded.list',
  'PRODUCT_ASSOCIATIONS_UPLOAD_PROCESSED': 'channel.:channel_uuid.product.association.upload.processed.list',

  'PRODUCT_ASSOCIATION_ADDED': 'channel.:channel_uuid.product.:product_uuid.association.added',
  'PRODUCT_ASSOCIATIONS_ADDED': 'channel.:channel_uuid.product.:product_uuid.association.added.list',
  'PRODUCT_ASSOCIATION_CREATED': 'channel.:channel_uuid.product.:product_uuid.association.created',
  'PRODUCT_ASSOCIATIONS_CREATED': 'channel.:channel_uuid.product.:product_uuid.association.created.list',
  'PRODUCT_ASSOCIATION_UPDATED': 'channel.:channel_uuid.product.:product_uuid.association.updated',
  'PRODUCT_ASSOCIATION_REMOVED': 'channel.:channel_uuid.product.:product_uuid.association.removed',
  'PRODUCT_ASSOCIATION_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.association.destroyed',

  'PRODUCT_ASSOCIATION_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.association.published',
  'PRODUCT_ASSOCIATION_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.association.unpublished',

  'PRODUCT_CATEGORY_ADDED': 'channel.:channel_uuid.product.:product_uuid.category.added',
  'PRODUCT_CATEGORY_REMOVED': 'channel.:channel_uuid.product.:product_uuid.category.removed',

  'PRODUCT_IMAGE_ADDED': 'channel.:channel_uuid.product.:product_uuid.image.added',
  'PRODUCT_IMAGES_ADDED': 'channel.:channel_uuid.product.:product_uuid.image.added.list',
  'PRODUCT_IMAGE_CREATED': 'channel.:channel_uuid.product.:product_uuid.image.created',
  'PRODUCT_IMAGES_CREATED': 'channel.:channel_uuid.product.:product_uuid.image.created.list',
  'PRODUCT_IMAGE_UPDATED': 'channel.:channel_uuid.product.:product_uuid.image.updated',
  'PRODUCT_IMAGE_REMOVED': 'channel.:channel_uuid.product.:product_uuid.image.removed',
  'PRODUCT_IMAGE_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.image.destroyed',
  'PRODUCT_IMAGES_UPLOADED': 'channel.:channel_uuid.product.:product_uuid.image.uploaded.list',
  'PRODUCT_IMAGE_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.image.published',
  'PRODUCT_IMAGE_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.image.unpublished',

  'PRODUCT_VARIANT_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.added',
  'PRODUCT_VARIANTS_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.added.list',
  'PRODUCT_VARIANT_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.created',
  'PRODUCT_VARIANTS_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.created.list',
  'PRODUCT_VARIANT_UPDATED': 'channel.:channel_uuid.product.:product_uuid.variant.updated',
  'PRODUCT_VARIANT_REMOVED': 'channel.:channel_uuid.product.:product_uuid.variant.removed',
  'PRODUCT_VARIANT_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.variant.destroyed',
  'PRODUCT_VARIANTS_UPLOADED': 'channel.:channel_uuid.product.:product_uuid.variant.uploaded.list',
  'PRODUCT_VARIANT_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.published',
  'PRODUCT_VARIANT_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.unpublished',
  'PRODUCT_VARIANTS_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.published.list',
  'PRODUCT_VARIANTS_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.unpublished.list',

  'PRODUCT_VARIANT_ASSOCIATION_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.association.added',
  'PRODUCT_VARIANT_ASSOCIATIONS_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.association.added.list',
  'PRODUCT_VARIANT_ASSOCIATION_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.association.created',
  'PRODUCT_VARIANT_ASSOCIATIONS_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.association.created.list',
  'PRODUCT_VARIANT_ASSOCIATION_UPDATED': 'channel.:channel_uuid.product.:product_uuid.variant.association.updated',
  'PRODUCT_VARIANT_ASSOCIATION_REMOVED': 'channel.:channel_uuid.product.:product_uuid.variant.association.removed',
  'PRODUCT_VARIANT_ASSOCIATION_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.variant.association.destroyed',
  'PRODUCT_VARIANT_ASSOCIATIONS_UPLOADED': 'channel.:channel_uuid.product.:product_uuid.variant.association.uploaded.list',
  'PRODUCT_VARIANT_ASSOCIATION_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.association.published',
  'PRODUCT_VARIANT_ASSOCIATION_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.association.unpublished',

  'PRODUCT_VARIANT_IMAGE_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.image.added',
  'PRODUCT_VARIANT_IMAGES_ADDED': 'channel.:channel_uuid.product.:product_uuid.variant.added.image.list',
  'PRODUCT_VARIANT_IMAGE_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.image.created',
  'PRODUCT_VARIANT_IMAGES_CREATED': 'channel.:channel_uuid.product.:product_uuid.variant.created.image.list',
  'PRODUCT_VARIANT_IMAGE_UPDATED': 'channel.:channel_uuid.product.:product_uuid.variant.image.updated',
  'PRODUCT_VARIANT_IMAGE_REMOVED': 'channel.:channel_uuid.product.:product_uuid.variant.image.removed',
  'PRODUCT_VARIANT_IMAGE_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.variant.image.destroyed',
  'PRODUCT_VARIANT_IMAGES_UPLOADED': 'channel.:channel_uuid.product.:product_uuid.variant.uploaded.image.list',
  'PRODUCT_VARIANT_IMAGE_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.image.published',
  'PRODUCT_VARIANT_IMAGE_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.variant.image.unpublished',

  'PRODUCT_VENDOR_ADDED': 'channel.:channel_uuid.product.:product_uuid.vendor.added',
  'PRODUCT_VENDORS_ADDED': 'channel.:channel_uuid.product.:product_uuid.vendor.added.list',
  'PRODUCT_VENDOR_CREATED': 'channel.:channel_uuid.product.:product_uuid.vendor.created',
  'PRODUCT_VENDORS_CREATED': 'channel.:channel_uuid.product.:product_uuid.vendor.created.list',
  'PRODUCT_VENDOR_UPDATED': 'channel.:channel_uuid.product.:product_uuid.vendor.updated',
  'PRODUCT_VENDOR_REMOVED': 'channel.:channel_uuid.product.:product_uuid.vendor.removed',
  'PRODUCT_VENDOR_DESTROYED': 'channel.:channel_uuid.product.:product_uuid.vendor.destroyed',
  'PRODUCT_VENDORS_UPLOADED': 'channel.:channel_uuid.product.:product_uuid.vendor.uploaded.list',
  'PRODUCT_VENDOR_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.vendor.published',
  'PRODUCT_VENDOR_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.vendor.unpublished',
  'PRODUCT_VENDORS_PUBLISHED': 'channel.:channel_uuid.product.:product_uuid.vendor.published.list',
  'PRODUCT_VENDORS_UNPUBLISHED': 'channel.:channel_uuid.product.:product_uuid.vendor.unpublished.list',
}
